version: 2.0
workflows:
  ios_build:
    name: iOS Build
    environment:
      xcode: latest
    scripts:
      - name: Install CocoaPods Dependencies
        script: |
          cd GenieD
          pod install
      - name: Clean Build
        script: |
          xcodebuild clean -workspace GenieD.xcworkspace -scheme GenieD
      - name: Build iOS App
        script: |
          xcodebuild -workspace GenieD.xcworkspace -scheme GenieD -sdk iphoneos -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
    artifacts:
      - GenieD/build/Release-iphoneos/*.ipa
