workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      xcode: latest
    scripts:
      - name: Install CocoaPods
        script: |
          sudo gem install cocoapods --no-document || true
      - name: Install dependencies
        script: |
          cd GenieD
          pod install
      - name: Build iOS app
        script: |
          cd GenieD
          xcodebuild \
            -workspace "GenieD.xcworkspace" \
            -scheme "GenieDScheme" \
            -sdk iphoneos \
            -configuration Release \
            -archivePath $CM_BUILD_DIR/GenieD.xcarchive \
            CODE_SIGN_IDENTITY="iPhone Developer" \
            PROVISIONING_PROFILE_SPECIFIER="your-provisioning-profile" \
            clean archive
    artifacts:
      - $CM_BUILD_DIR/GenieD.xcarchive
    publishing:
      email:
        recipients:
          - rubelrana019914@gmail.com
